---
title: "Nam's Website"
output: html_document
---

<style type="text/css">

.title {
  display: none;
}

#getting-started img {
  margin-right: 10px;
}

.container-full {
  width: auto;
  margin: 0;
  padding: 0;
}

.full-width {
  width: 100%;
}

body, html {
  height: 100%;
  margin: 0;
}

.row {
  margin: 0;
}

</style>

<div class="container-full">
<div class="row" style="padding-top: 30px;">

# **The Missing Semester of Your Economics Degree** 
<hr/>

# About us 

We are a student-led organization that seeks to promote student-centered economics research at Carleton University. 

## Mission

Participating in the research process can be difficult - especially in economics. Unlike other disciplines, it can take time -years- to learn all the necessary material to produce good research. But when you do get to learning all that material, what then? Where do you look to find the most up-to-date papers in your discpline? How do you get funding so that you can paid for your work? How do you email a supervisor and pitch your ideas? How do you come up with those ideas in the first place? 

During the summer of 2024, a group of undergraduate and graduate students got together to brainstorm about how to make economics research more accessible to students. What they came up with was an organization that could help **connect**, **educate**, and **promote** economics research to anyone that was willing to learn. 

The need for a organization, <u> of the students </u>, <u> by the students </u>, and <u> for the students </u> of Carleton University was beginning to make more and more sense. 

Our most cherished values are at the core of our services: ensuring that  academic research, its processes, the knowledge it generates and network it builds, are freely accessible to any student who pursues it. 

### Core Services
Our organization hosts our services under three broad categories:  

  1) Advocate
  2) Educate
  3) Affiliate

#### Advocate
<em>Why should students get into academic research?</em> <br/>
This is an important question to bear in mind. The answer is not completely obvious to every student. For that reason, we have come up with services that advocate for a student-centered approach to economics research. Some services include:

  a) <u>Featured Student Researchers</u>: a page that features the work of student researchers and its importance to them,
  b) <u>Content Creation</u>: written content by students about the research process and the skills gained from engaging in it,
  c) <u>Research Opportunities</u>: research opportunities available to students and the experiences of those who have already taken part in them.  

#### Educate
<em>How do students learn how to produce good research?</em> <br/>
We recognized the enormity of taking the first step for students, especially those who's only exposure to research was from a single class. For that reason, we wanted to offer an educational pathway that could provide an intelligent plan for students to follow. Some services include:

  a) <u>Learning Pathways</u>: a page that summarizes material learned in the classroom and translates it to material found in published research  
  b) <u>Experiential Learning</u>: walk-through projects that replicate research conducted by students or faculty

#### Affiliate
<em>How do I get help or get my questions answered?</em> <br/>
Having someone to talk you through building a solid academic portfolio, or being able to connect with faculty is vital. For this reason, we wanted to encourage collaboration between students, faculty, and other stakeholders:

  a) <u>Mentoring</u>: this page will contain our roster of featured mentors
  
  b) <u>Featured Professors</u>: this page will feature the work of some economics professors with their work presented in such a way to be highly accessible to students 
  <hr> </hr>
To learn more about our core services, please click on one of the tabs at the top of the webpage. 
</div>
</div>
</div>