---
title: "Sample: RA Training"
output: html_document
---

<style>
/* Import Google Fonts */
@import url('https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;700&display=swap');

/* Global Styles */
body {
  <!-- text-align: center; -->
  background-color: #FFFFFF; /* White background */
  font-family: 'Open Sans', Arial, sans-serif;
  color: #333333; /* Dark gray text */
}

/* Header Style */
h1 {
  font-size: 2.5em;
  color: #990000; /* Carleton red */
  margin-bottom: 0.5em;
}

img {
  width: 400px;
  height: 400px;
  <!-- border-radius: 50%; -->
  <!-- object-fit: cover; -->
  <!-- object-position: center; -->
  <!-- margin-bottom: 10px; -->
}

p {
  color: #333333;
  line-height: 1.6;
  text-align: justify;
  margin: 0 auto 20px auto;
}

</style>

We believe that one of the best ways for students to learn economics is through working as a research assistant. 

This is why we want to build a system that trains students to become budding researchers through workshops and collaborative projects. 

This [article](https://www.povertyactionlab.org/sites/default/files/Advice-for-Landing-an-RA-ship.pdf) by the poverty action lab describes many great reasons to pursue research assistant work: 

  1. Skills: Students will get to learn skills that prepare them to become economic researchers.
  2. Research Exposure: Students get hands-on training to cutting-edge research with Carleton's faculty. 
  3. Knowledge: Students get to see the theory that they are learning at work.
  4. Impact: Students get to use what they learn to make a difference in their community.
  
<hr>

## Proof-of-Concept: Carleton Research Assistant Training Program 
<p>
<em>
"I have a data set that I've collected that I want you to analyze. You'll need to preprocess the data as it's pretty messy. Once you're done with that, run a linear regression on some variables that you find interesting. Present your finding to me in a clear and effective manner." 
</em>
</p>

These are imaginary instructions that you may receive when you're asked to do work as a research assistant. If you had to do this for the first time, would you know where to start? 
We've got you covered, because in this module, we'll be going through the tools that you need to get this to work. 